import assert from 'node:assert/strict';
import {createEmojis} from '../src/emojis.mjs';
globalThis.window={dispatchEvent(){}};
const png='data:image/png;base64,iVBORw0KGgo=';
const jsx=(type,props,key)=>({type,props,key});
let requests=0;
const api=createEmojis({jsxRuntime:{jsx},read:async()=>{requests++;return {items:{'[测试]':png,'[远程]':'https://example.invalid/a','bad':png}};}});
await Promise.all([api.load({}),api.load({})]); assert.equal(requests,1);
const input='constructor <img onerror=alert(1)>[测试]👍[未知]';
assert.equal(api.parts(input).join(''),input);
const nodes=api.Text({text:input});
assert.equal(nodes.filter(n=>typeof n==='object').length,1);
assert.equal(nodes.find(n=>typeof n==='object').props.src,png);
assert.equal(nodes.find(n=>typeof n==='object').props.alt,'[测试]');
assert.ok(nodes.includes('👍')); assert.ok(nodes.includes('[未知]'));
assert.equal(Object.getPrototypeOf(api.catalog),null);
assert.equal(api.catalog['[远程]'],undefined);
let failures=0;
const retry=createEmojis({jsxRuntime:{jsx},read:async()=>{if(!failures++)throw Error('offline');return {items:{'[测试]':png}};}});
await retry.load({}); await retry.load({}); assert.equal(retry.catalog['[测试]'],png);
console.log('PASS emoji known/unknown/Unicode, safe text, local PNG, request dedup and retry');
